### ISSUE TITLE
Made database using mysql, but search and users dont work and do not know how to use th wierd image that i do not understand for databse branches

### ISSUE THREAD

**Issue by nah094** [Dhyeythumar/Search_Engine#3] opened 2021-04-09 13:30 UTC
Hi. Im really sorry but can you tell me how to make the database actually do somthing. it connected. but it does nothing and search does not work. plz fix. I would like to use this locally and make edits so i can learn and make my own.

**Comment by dhyeythumar** [comment] 2021-04-09 13:47
I am using `mysql2` lib which only helps in executing queries to the DB from code. And no schema is defined from code (I did create tables directly from MYSQL workbench) so the tables wont be created directly from code!
And to get search results you also need data in your DB.

Are you looking for production level search engine? Then I think this project is not sufficient for that, I have created this as a hobby project 😅.

**Comment by nah094** [comment] 2021-04-09 13:49
I know and thanks!

**Comment by dhyeythumar** [comment] 2021-04-09 13:49
But definitely I will improve this project over the time (i.e adding code for DB schema and other improvements)

**Comment by nah094** [comment] 2021-04-09 13:50
Thanks

**Comment by nah094** [comment] 2021-04-09 13:53
How do yo connet a web crawler?

**Comment by dhyeythumar** [comment] 2021-04-09 13:58
You don't need to connect a web crawler with node.js code. What I did was, I ran python crawler and it kept adding data into DB. So both of them can be running separately.

**Comment by nah094** [comment] 2021-04-09 13:59
Should i create alll the tables and how do i add search to database

**Comment by dhyeythumar** [comment] 2021-04-09 14:01
Yes you have to create all the tables according to the DB schema. I didn't get your second question.

**Comment by nah094** [comment] 2021-04-09 14:02
How do iadd search results to database, sorry for not being clear

**Comment by dhyeythumar** [comment] 2021-04-09 14:07
As I said for me data (websites meta data) was populated by the scraper (I haven't pushed it on this repo for security concerns because I don't know if the scraper is right thing to upload on github).

**Comment by nah094** [comment] 2021-04-09 14:08
How can I activate scrapy then?

**Comment by dhyeythumar** [comment] 2021-04-09 14:10
If you want I can share the scraper, but not over github.

**Comment by nah094** [comment] 2021-04-09 14:11
What would we use?

**Comment by dhyeythumar** [comment] 2021-04-09 14:12
You can give me your email, I will send the python file over there.

**Comment by nah094** [comment] 2021-04-09 14:14
I will give temp mail and can you also give inscrution with email thanks

email: xidiyeb606@whyflkj.com

**Comment by nah094** [comment] 2021-04-09 14:31
Thank you for the files and an ad to bitcoin? Thanks a million

**Comment by nah094** [comment] 2021-04-09 14:38
It still does not search i repaced the files and connected to my database but no autocomplete or no search works :sob:

**Comment by dhyeythumar** [comment] 2021-04-11 03:14
As I said you have to create tables first and then use `scraper.py` to collect data (this will store data in json files), after this you have to run `database_conn.py` file to put the json data from file to DB.

**Comment by divyanshrai655** [comment] 2021-04-25 19:41
@Dhyeythumar Can I get the code you used for your DB Schema (my email is divyansh2509@gmail.com) , would be greatful , also after creating DB using the code would I be requiring something else to make the Engine Run.I just advice you using making an Video about installation and usage for future would be helpful to others :P

**Comment by dhyeythumar** [comment] 2021-04-26 03:48
Hi @Lazy-Leopard, So I have used raw SQL queries to create tables (you can also use MYSQL workbench to create tables). And after creating, the tables you need to have data in your tables to do any search operations. 

I am planning to update this project (so I might change DB schema and even use MongoDB Atlas) & probably host the project. So the video will become obsolete.

So if you want to contribute, then I am more than happy to some interesting PRs 🙂.

**Comment by divyanshrai655** [comment] 2021-04-26 04:26
For convenience I wanted to use your SQL Queries to create my Database.
So that don't have to brainstorm much.
I am even interested on contributing to this,but seeking help for setup.
@Dhyeythumar

**Comment by dhyeythumar** [comment] 2021-04-26 04:50
It's been 2 years that I haven't developed anything new in this project & now I do not even have those SQL queries with me.

But the queries are straightforward & you can reproduce them with the help of the Relational Schema given in point 2 [**here**](https://github.com/Dhyeythumar/Search-Engine/blob/master/database_schema.md#database-schema).

I have also mentioned steps to setup the project in the readme, but I think I forget to mention that one has to create the DB tables using raw SQL queries.

If you get any doubts, then feel free to ask ✌.

**Comment by dhyeythumar** [comment] 2021-05-15 03:38
I hope the questions are resolved ✌🏻. I am closing this issue, but if you have any further more questions then you can reopen it.

**Closed as completed by dhyeythumar** 2021-05-15 03:38 UTC
